services:
  qr-backend:
    build: backend/
    environment:
      PYTHONIOENCODING: UTF-8
      PYTHONFAULTHANDLER: 1
    working_dir: /src
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 --log-level debug project.wsgi
    tty: true
    stdin_open: true
    restart: always

  qr-backend-celery:
    build: backend/
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
      PYTHONIOENCODING: UTF-8
      PYTHONFAULTHANDLER: 1
    working_dir: /src
    command: celery -A project.celery worker -l INFO
    tty: true
    stdin_open: true
    restart: always

  qr-backend-celerybeat:
    build: backend/
    environment:
      DJANGO_SETTINGS_MODULE: project.settings
      PYTHONIOENCODING: UTF-8
      PYTHONFAULTHANDLER: 1
    working_dir: /src
    command: celery -A project.celery beat -l INFO
    tty: true
    stdin_open: true
    restart: always

  qr-nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

  redis:
    image: redis:8
    restart: always