# Generated by Django 5.1.1 on 2025-01-01 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_redirect', models.URLField()),
                ('link_hash', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
