# Generated by Django 5.1.1 on 2025-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrlink',
            name='link_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
